import React from "react";
import Link from "next/link";
import Head from "next/head";
import { useRouter } from 'next/router'

export default function Nav({ children }) {
  const router = useRouter()
  const currentRoute = router.pathname
  return (
    <div className="fullNav">
      <Head>
        <title>Passport Legacy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"/>
      </Head>
      <div className="topnav">
      <img style={{width:"25px"}} src="clock.svg"/>
      <div style={{flexDirection:"row", color:"#fff", paddingLeft:"10px", fontSize:"12px"}}>
        <div>24 Hours</div>
        <div>Opening hours Sun-Thu</div>
      </div>
    <div style={{flexDirection:"row",display:"flex",paddingLeft:"20px"}}>
      <img style={{width:"25px"}} src="whatsapp.svg"/>
      <div style={{flexDirection:"row", color:"#fff", paddingLeft:"10px", fontSize:"12px"}}>
        <div>+971 50 404 6269</div>
        <div>Call us for free consultation</div>
      </div>
      </div>
      <div style={{paddingLeft:"20px"}}>
      <img style={{width:"20px"}} src="facebook.png"/>
      </div>
      <div style={{paddingLeft:"10px"}}>
      <img style={{width:"20px"}} src="facebook.png"/>
      </div>
      <div style={{paddingLeft:"10px"}}>
      <img style={{width:"20px"}} src="facebook.png"/>
      </div>
      <div style={{paddingLeft:"10px"}}>
      <img style={{width:"20px"}} src="facebook.png"/>
      </div>
      <div style={{paddingLeft:"10px"}}>
      <img style={{width:"20px"}} src="facebook.png"/>
      </div>
    </div>
      <nav>
        <div className="logo"><img src="logo.png"/></div>
        <input type="checkbox" id="click" />
        <label for="click" className="menu-btn">
          <i className="fas fa-bars"></i>
        </label>
        <ul style={{marginBottom:"0px"}}>
          <li>
          <Link href="/home">
            <a className={currentRoute === '/home' ? 'active' : ''}>
              HOME
            </a>
            </Link>
          </li>
          <li>
          <Link href="/about">
            <a className={currentRoute === '/about' ? 'active' : ''}>ABOUT US</a>
            </Link>
          </li>
          <li>
          <Link href="/about">
            <a className={currentRoute === '/about' ? 'active' : ''}>PROGRAMS</a>
            </Link>
          </li>
          <li>
          <Link href="/about">
            <a className={currentRoute === '/about' ? 'active' : ''}>BENEFITS</a>
            </Link>
          </li>
          <li>
          <Link href="/about">
            <a className={currentRoute === '/about' ? 'active' : ''}>FAQ</a>
            </Link>
          </li>
          <li>
          <Link href="/about">
            <a className={currentRoute === '/about' ? 'active' : ''}>BLOG</a>
            </Link>
          </li>
          <li>
          <Link href="/about">
            <a className={currentRoute === '/about' ? 'active' : ''}>WORLDWIDE NETWORKS</a>
            </Link>
          </li>
          <li>
          <Link href="/about">
            <a className={currentRoute === '/about' ? 'active' : ''}>CONTACT US</a>
            </Link>
          </li>
          <li>
          <Link href="/about">
            <a style={{backgroundColor:"#E3AB50"}}>CITIZENSHIP ENQUIRY</a>
            </Link>
          </li>
        </ul>
      </nav>
      
    </div>
  );
}
