import React from "react";
import Head from 'next/head';
import emailjs from 'emailjs-com';

export default function Citizenship({ posts }) {
  function sendEmail(e) {
    e.preventDefault();

    emailjs.sendForm('service_zpt2a9x', 'template_9uw13mo', e.target, 'user_L3cHM0q2gc2WbGqCrbrJx')
      .then((result) => {
          console.log(result.text);
      }, (error) => {
          console.log(error.text);
      });
      e.target.reset()
  }
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous"/>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.3/css/fontawesome.min.css" integrity="sha384-wESLQ85D6gbsF459vf1CiZ2+rr+CsxRY0RpiF1tLlQpDnAgg6rwdsUF1+Ics2bni" crossorigin="anonymous"/>
      </Head>

      <section class="section-padding" style={{backgroundColor: "#ECECEC",}} id="about">
                <div class="container" style={{backgroundColor: "#ECECEC",}}>
                    <div class="row">

                        <div class="col-lg-6 col-md-6 col-12">

                            <p
              style={{
                color: "#0E2043",
                backgroundColor: "#ECECEC",
                fontSize: "22px",
                fontWeight: "700",
                textAlign: "justify"
              }}
            >
              If you are looking to enjoy exactly these benefits, Passport
              Legacy is here to assist you with your second citizenship.{" "}
            </p>
            <p
              style={{
                color: "#0E2043",
                paddingTop: "30px",
                backgroundColor: "#ECECEC",
                textAlign: "justify"
              }}
            >
              If you would like more information about any of the qualifying
              programs, or our services, please do not hesitate to contact us.
            </p>
                        </div>

                        <div class="col-lg-5 col-md-5 col-12 mx-auto" >
                        <form onSubmit={sendEmail}>
                        <div style={{paddingBottom:"5px"}}>
                            <input class="form-control contactInput"  type="text" placeholder="Name" name="name"/>
                            </div>
                        <div style={{paddingBottom:"5px"}}>

                            <div class="row">
                            <div class="col-md-6">
                                <input type="text" class="form-control contactInput"  placeholder="Email" name="email"/>
                              </div>
                              <div class="col-md-6">
                                <input type="text" class="form-control contactInput"  placeholder="Phone" name="phone"/>
                              </div>
                            </div>
                            </div>
                        <div style={{paddingBottom:"5px"}}>

                            <input class="form-control contactInput"  type="text" placeholder="Subject" name="subject"/>
                            </div>
                            <div style={{paddingBottom:"5px"}}>
                            <textarea class="form-control contactInput"  placeholder="Message" rows="4" name="message"></textarea>
                            </div>
                            <input class="form-control contactInput" style={{backgroundColor:"#0E2043", color:"#fff", textAlign:"center"}}  type="submit" value="Submit"/>

</form>
                        </div>

                    </div>
                </div>
            </section>
    </>
  )
}