import React from "react";
import InstagramEmbed from "react-instagram-embed";
import Head from 'next/head'

export default function Features({ posts }) {
  return (
    <>
    <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous"/>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.3/css/fontawesome.min.css" integrity="sha384-wESLQ85D6gbsF459vf1CiZ2+rr+CsxRY0RpiF1tLlQpDnAgg6rwdsUF1+Ics2bni" crossorigin="anonymous"/>
      </Head>
    <div className="container">
      <div className="row" style={{paddingBottom: "60px"}}>
        <div className="col-md-2 text-center" >
          <div className="icon" style={{marginBottom: "10px",color:"#000"}}>
            <img src="visaBlue.svg" />
          </div>
          <h6>VISA-FREE</h6>
        </div>
        <div className="col-md-2 text-center">
          <div className="icon" style={{marginBottom: "10px"}}>
             <img src="educationBlue.svg" />
          </div>
          <h6>EDUCATION</h6>
        </div>
        <div className="col-md-2 text-center">
          <div className="icon" style={{marginBottom: "10px"}}>
             <img src="taxBlue.svg" />
          </div>
          <h6>TAX-BENEFITS</h6>
        </div>
        <div className="col-md-2 text-center">
          <div className="icon" style={{marginBottom: "10px"}}>
             <img src="globalBlue.svg" />
          </div>
          <h6>GLOBAL BUSINESS</h6>
        </div>
        <div className="col-md-2 text-center">
          <div className="icon" style={{marginBottom: "10px"}}>
             <img src="planBlue.svg" />
          </div>
          <h6>PLAN B</h6>
        </div>
        <div className="col-md-2 text-center">
          <div className="icon" style={{marginBottom: "10px"}}>
             <img src="futureBlue.svg" />
          </div>
          <h6>FUTURE GENERATIONS</h6>
        </div>
      </div>
      {/* <div className="benefitsContainer"></div> */}
    </div>
    </>
  );
}

