import Head from "next/head";
import React from "react";

export default function Video({ posts }) {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous"/>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.3/css/fontawesome.min.css" integrity="sha384-wESLQ85D6gbsF459vf1CiZ2+rr+CsxRY0RpiF1tLlQpDnAgg6rwdsUF1+Ics2bni" crossorigin="anonymous"/>
      </Head>

      <section class="section-padding" id="about" style={{backgroundColor:"#0E2043"}}>
                <div class="container">
                    <div class="row">

                        <div class="col-lg-6 col-md-6 col-12">
                            <h2 class="mb-lg-3 mb-3" style={{fontSize: "42px", color:"#fff"}}>How to get your second passport?</h2>

                            <p style={{color:"#fff"}}>We provide a range of professional services to our private clients
                                including the acquisition of alternative residence or citizenship
                                as well as real estate.</p>

                        </div>

                        <div class="col-lg-5 col-md-5 col-12 mx-auto">
                            <video width="100%" height="100%" controls>
                              <source src="PassportVid.mp4" type="video/mp4"/>
                            </video>
                        </div>

                    </div>
                </div>
            </section>
    </>
  );
}
